name: wallabag
options:
  bundleIdPrefix: "fr.district-web"
settings:
  DEVELOPMENT_TEAM: G97URPCGB8
  IPHONEOS_DEPLOYMENT_TARGET: 11.0
configFiles:
  Debug: configs/Debug.xcconfig
  Release: configs/Release.xcconfig
targets:
  wallabag:
    type: application
    platform: iOS
    deploymentTarget: "11.0"
    sources: [wallabag]
    dependencies:
      - target: bagit
      - target: WallabagCommon
      - target: WallabagKit
    configFiles:
      Debug: configs/wallabag-Debug.xcconfig
      Release: configs/wallabag-Release.xcconfig
    postbuildScripts:
      - script: swiftlint
        name: Swiftlint
      - script: |
                "${PODS_ROOT}/Fabric/run" 0207ff96630ec7ce562a1b658bd7bd2a0f8024a3 e655dde9ee1422229d8c0589d0596ba3c3e0641d994a75ea76a048cb981288bb
        name: fabricio
  bagit:
    type: app-extension
    platform: iOS
    deploymentTarget: "11.0"
    sources: 
      - bagit
      - wallabag/Assets.xcassets
    configFiles:
      Debug: configs/bagit-Debug.xcconfig
      Release: configs/bagit-Release.xcconfig
    options:
      bundleIdPrefix: "fr.district-web.wallabag"
    dependencies:
      - target: WallabagCommon
      - target: WallabagKit
  wallabagUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [wallabagUITests]
    dependencies:
      - target: wallabag
    configFiles:
      Debug: configs/wallabagUITests-Debug.xcconfig
      Release: configs/wallabagUITests-Release.xcconfig
  wallabagTests:
    type: bundle.unit-test
    platform: iOS
    configFiles:
      Debug: configs/wallabagTests-Debug.xcconfig
      Release: configs/wallabagTests-Release.xcconfig
    sources: [wallabagTests]
    dependencies:
      - target: wallabag
  WallabagCommon:
    type: framework
    platform: iOS
    sources: [wallabagCommon]
  WallabagKit:
    type: framework
    platform: iOS
    sources: [wallabagKit]
schemes:
  WallabagTest:
    build:
      targets:
        wallabag: all
    test:
      targets: [wallabagTests]