name: wallabag
options:
  bundleIdPrefix: "fr.district-web"
settings:
  DEVELOPMENT_TEAM: G97URPCGB8
#  PRODUCT_BUNDLE_IDENTIFIER: fr.district-web.wallabag
targets:
  wallabag:
    type: application
    platform: iOS
    deploymentTarget: "11.0"
    sources: [wallabag]
    dependencies:
      - target: bagit
      - target: WallabagCommon
      - target: WallabagKit
    settings:
      SWIFT_OBJC_BRIDGING_HEADER: "wallabag/Lib/wallabag-Bridging-Header.h"
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
      CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
  bagit:
    type: app-extension
    platform: iOS
    deploymentTarget: "11.0"
    sources: bagit
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "fr.district-web.wallabag"
    options:
      bundleIdPrefix: "fr.district-web.wallabag"
    dependencies:
      - target: WallabagCommon
      - target: WallabagKit
  wallabagUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "11.0"
    sources: [wallabagUITests]
    dependencies:
      - target: wallabag
  wallabagTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "11.0"
    sources: [wallabagTests]
    dependencies:
      - target: wallabag
  WallabagCommon:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [wallabagCommon]
  WallabagKit:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [wallabagKit]