name: wallabag
settings:
  DEVELOPMENT_TEAM: G97URPCGB8
  PRODUCT_BUNDLE_IDENTIFIER: fr.district-web.wallabag
targets:
  wallabag:
    type: application
    platform: iOS
    deploymentTarget: "11.0"
    sources: [wallabag]
    dependencies:
      - target: bagit
      - target: WallabagCommon
      - target: WallabagKit
    settings:
      SWIFT_OBJC_BRIDGING_HEADER: "wallabag/Lib/wallabag-Bridging-Header.h"
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
  bagit:
    type: app-extension
    platform: iOS
    deploymentTarget: "11.0"
    sources: bagit
  wallabagUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "11.0"
    sources: [wallabagUITests]
  wallabagTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "11.0"
    sources: [wallabagTests]
  WallabagCommon:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [wallabagCommon]
  WallabagKit:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [wallabagKit]